[package]
name = "md22"
version = "0.1.0"
authors = ["James Clarke <james.e.clarke@sheffield.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.4"
embedded-hal-mock = "0.7.2"