[package]
name = "md22"
version = "0.1.0"
authors = ["James Clarke <james.clarke@klarke.co.uk>"]
edition = "2018"
description = "An MD22 motor driver which uses I2C via embedded-hal."
license = "MIT OR Apache-2.0"


[dependencies]
embedded-hal = "0.2.4"
embedded-hal-mock = "0.7.2"